---
- name: Apply base system configuration
  include_role:
    name: base

- name: Setup Redis repository
  include_tasks: repository.yml

- name: Install and configure Redis
  include_tasks: redis.yml

