---
- name: Install Redis
  apt:
    name: redis
    state: present

- name: Configure Redis to bind only to the provided IP
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind\s+.*'
    line: "bind 127.0.0.1 {{ redis_bind_ip }}"
    state: present
    backup: yes
  register: redis_bind
  notify: restart redis

- name: Ensure protected-mode is enabled
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^protected-mode\s+.*'
    line: "protected-mode yes"
    state: present
  register: protected_mode
  notify: restart redis

- name: Start and enable Redis
  service:
    name: redis-server
    state: started
    enabled: true

