---
# Kibana core configuration via template
- name: Configure Kibana (complete configuration via template)
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: "{{ '0640' if elasticsearch_secure_permissions | default(true) else '0660' }}"
    backup: yes
  notify: restart kibana 