---
# Redis Core Configuration
- name: Configure Redis to bind only to the provided IP
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind\s+.*'
    line: "bind 127.0.0.1 {{ redis_bind_ip }}"
    state: present
    backup: yes
  register: redis_bind
  notify: restart redis

- name: Configure Redis port
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^port\s+.*'
    line: "port {{ redis_port }}"
    state: present
  notify: restart redis

- name: Configure Redis maximum memory (60% of available RAM)
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^maxmemory\s+.*'
    line: "maxmemory {{ [256, (ansible_memtotal_mb * 0.6) | int] | max }}mb"
    state: present
  notify: restart redis 