---
- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Configure Elasticsearch network settings
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#?\s*network\.host:.*'
    line: "network.host: 127.0.0.1, {{ elasticsearch_bind_ip }}"
    state: present
    backup: yes
  register: network_config
  notify: restart elasticsearch

- name: Configure Elasticsearch security settings
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#?\s*xpack\.security\.enabled:.*'
    line: "xpack.security.enabled: false"
    state: present
  register: security_config
  notify: restart elasticsearch

- name: Configure Elasticsearch discovery settings
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#?\s*discovery\.type:.*'
    line: "discovery.type: single-node"
    state: present
  register: discovery_config
  notify: restart elasticsearch

- name: Remove cluster.initial_master_nodes if present
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^cluster.initial_master_nodes:.*'
    state: absent
  register: cluster_config
  notify: restart elasticsearch

- name: Start and enable Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: true

