---
- name: Download Redis GPG key (ASCII format)
  get_url:
    url: https://packages.redis.io/gpg
    dest: /tmp/redis.gpg
    mode: '0644'

- name: Convert Redis GPG key to binary and move to keyrings dir
  shell: |
    gpg --dearmor -o /etc/apt/keyrings/redis-archive-keyring.gpg /tmp/redis.gpg
  args:
    creates: /etc/apt/keyrings/redis-archive-keyring.gpg

- name: Add Redis APT repository with signed-by
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb {{ ansible_distribution_release | lower }} main"
    filename: redis
    state: present

- name: Update APT cache
  apt:
    update_cache: yes

